config/routes.rb
Rails.application.routes.draw do

      # 顧客用
    # URL /customers/sign_in ...
    devise_for :customers, skip: [:passwords],controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

    scope module: :public do
    	root to:"homes#top"
    end

    #public/customers
    scope module: :public do
      get 'customers/my_page' => 'customers#show', as: 'my_page'
      get 'customers/information/edit' => 'customers#edit'
      patch 'customers/information' => 'customers#update', as: 'information'
      get 'customers/bookmark' => "customers#bookmark", as: 'bookmark' #ブックマーク一覧ページ
      get 'customers/confirm' => "customers#confirm", as: 'confirm' #退会確認ページ
      patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw' #退会処理
    end

    #ゲストログインのルーティング
    devise_scope :customer do
      post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
    end


    #public/orders
    scope module: :public do
      post '/orders/confirm' => "orders#confirm"
      get '/orders/complete' => 'orders#complete', as: 'complete'
      resources :orders, only: [:new, :create, :index, :show, :edit, :destroy, :update]
    end

    scope module: :public do
      delete "cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all" #「resources:cart_items」の上にdestroy_allを持ってきたらidがつかない
      resources :cart_items, only: [:index,:update,:destroy,:create]
      resources :shipping_addresses
      get '/items/searches' => 'items#searches', as: 'searches'
      resources :items
      resources :genres, only: [:show]
      resources :contacts, only: [:new, :create, :index, :show]
      post '/contacts/confirm' => "contacts#confirm"
      post '/contacts/back' => "contacts#back", as: "back"

      resources :shops do
        member do
          get :items
        end
        resource :bookmarks, only: %i[create destroy]
      end

    end


    # 管理者用
    # URL /admin/sign_in ...
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }

    namespace :admin do
      resources :genres
      resources :items
      resources :shops
      resources :customers
      resources :orders
      resources :contacts, only: [:index, :show, :update]
    end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre, optional: true
  belongs_to :shop
  has_many :cart_items

  validates :image, presence: true
  validates :name, presence: true
  validates :detail, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  validates :shop_id, presence: true

  def with_tax_price
    (price*1.1).floor
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    if @item.save
      flash[:notice] = "商品の新規登録が完了しました！"
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items=Item.page(params[:page])
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品の編集内容を保存しました！"
      redirect_to admin_item_path(@item.id)
    else
      render "edit"
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :detail, :genre_id, :shop_id, :price, :status)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class='container py-5'>
  <div class="row">
    <div class="col mt-3 text-center">
      <h4 class="font-weight-bold">商品編集</h4>
    </div>
  </div>
      <% if @item.errors.any? %>
         <%= @item.errors.count %>件のエラーが発生しました
        <ul>
         <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
         <% end %>
        </ul>
      <% end %>
</div>

<div class="row d-flex justify-content-center">
  <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
   <div class"col-md-6">
      <table class="table text-center">
        <tbody>
            <tr>
              <th><%= f.label "商品画像" %></th>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>

            <tr>
              <th><%= f.label "ショップ名"%></th>
              <td><%= f.select :shop_id, options_from_collection_for_select(Shop.all, :id, :name_display) %></td>
            </tr>

            <tr>
              <th><%= f.label "商品名"%></th>
              <td><%= f.text_field :name %></td>
            </tr>

            <tr>
              <th><%= f.label "商品説明"%></th>
              <td><%= f.text_area :detail %></td>
            </tr>

            <tr>
              <th><%= f.label "ジャンル" %></th>
              <td><%=f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></td>
            </tr>

            <tr>
              <th><%= f.label "税抜き価格" %></th>
              <td><%= f.text_field :price %>円</td>
            </tr>

            <tr>
              <th><%=f.label:"販売ステータス" %></th>
              <td><%= f.radio_button :status, :true %>
               <%= f.label :status, "販売中", {value: :true, style: "display: inline-block;"} %>
               <%= f.radio_button :status, :false %>
               <%= f.label :status, "販売停止中", {value: :false, style: "display: inline-block;"} %>
              </td>
            </tr>
        </tbody>
      </table>
   </div>
   <div class="row pb-5 d-flex justify-content-center">
        <%= f.submit "変更を保存", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 m-4 text-center">
      <h4 class="font-weight-bold">商品一覧</h4>
    </div>
    <div class="col-12 pb-3">
      <%=link_to "商品を追加する", new_admin_item_path, class: "btn btn-outline-warning rounded-pill" %>
    </div>
  </div>

  <table class='table table-inverse text-center'>
    <thead class="thead-dark">
      <tr>
        <th>商品ID</th>
        <th>ショップID/ショップ名</th>
        <th>商品名</th>
        <th>税抜き価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= item.shop.name_display %></td>
          <td>
            <%=link_to admin_item_path(item.id) do %>
              <%= item.name %>
            <% end %>
          </td>
          <td><%= item.price.to_s(:delimited) %></td>
          <td><%= item.genre.name %></td>
          <% if item.status == true %>
            <td class="text-success"><strong>販売中</strong></td>
          <% else %>
            <td class="text-danger"><strong>販売停止中</strong></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="container py-5" >
  <div class="row">
    <div class="col mb-5 mt-3 text-center">
      <h4 class="font-weight-bold">新規商品登録</h4>
    </div>
    <div class="col-12">
      <% if @item.errors.any? %>
        <%= @item.errors.count %>件のエラーが発生しました
        <ul>
          <% @item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <div class="row d-flex justify-content-center">
    <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

      <table class="table text-center" style="margin:auto;">
        <tbody>
          <tr>
             <th><%= f.label "ショップ名" %></th>
             <td><%= f.select :shop_id, options_from_collection_for_select(Shop.all, :id, :name_display) %></td>
             <!--name_displayについてはshopモデルに記載-->
          </tr>

          <tr>
             <th><%= f.label "商品画像" %></th>
             <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>

          <tr>
             <th><%= f.label "商品名"%></th>
             <td><%= f.text_field :name, placeholder: "商品名" %></td>
          </tr>

          <tr>
             <th><%= f.label "商品説明"%></th>
             <td><%= f.text_area :detail,placeholder: "ここに説明文を記述します" %></td>
          </tr>

          <tr>
             <th><%= f.label "ジャンル" %></th>
             <td><%=f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), include_blank: '選択してください' %></td>
          </tr>

          <tr>
             <th><%= f.label "税抜き価格"%></th>
             <td><%= f.text_field :price, placeholder: "1000" %></td>
          </tr>

          <tr>
             <th><%=f.label:"販売ステータス" %></th>
             <td>
                <%= f.radio_button :status, :true %>
                <%= f.label :status, "販売中", {value: :true, style: "display: inline-block;"} %>
                <%= f.radio_button :status, :false %>
                <%= f.label :status, "販売停止中", {value: :false, style: "display: inline-block;"} %>
             </td>
          </tr>
        </tbody>
      </table>

      <div class="row d-flex justify-content-center">
        <%= f.submit "新規登録", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class='container py-5'>
  <div class="row">
    <div class="col mb-3 mt-3 text-center">
      <h4 class="font-weight-bold">商品詳細</h4>
      <div class="flash text-center"><%= flash[:notice] %></div>
    </div>

        <div class="col-lg-10 offset-2 d-flex justify-content-start">
          <%= image_tag @item.image, size: "300x300" %>
            <div class="col-lg-5 pl-5">
              <table class="table ml-8">
                <tbody>
                  <tr>
                    <th>ショップ名</th>
                    <td><%= @item.shop.name_display %></td>
                  </tr>

                  <tr>
                    <th>商品名</th>
                    <td><%= @item.name %></td>
                  </tr>

                  <tr>
                    <th>商品説明</th>
                    <td><%= @item.detail %></td>
                  </tr>

                  <tr>
                    <th>ジャンル</th>
                    <td><%= @item.genre.name %></td>
                  </tr>

                  <tr>
                    <th>税込価格</br>(税抜価格)</th>
                    <td style=" vertical-align: middle; "><%=@item.with_tax_price.to_s(:delimited) %> (<%=@item.price.to_s(:delimited) %>)円</td>
                  </tr>

                  <tr>
                    <th class='text-nowrap'>販売ステータス</th>
                    <% if @item.status? %>
                    <td class="text-success text-center"><strong>販売中</strong></td>
                    <% else %>
                    <td class="text-black-50">販売停止中</td>
                    <% end %>
                  </tr>

                  <tr>
                    <th></th>
                    <th class="text-center"><%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-outline-primary btn-sm" %></th>
                  </tr>

                </tbody>
              </table>
            </div>
        </div>