config/routes.rb
Rails.application.routes.draw do

      # 顧客用
    # URL /customers/sign_in ...
    devise_for :customers, skip: [:passwords],controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

    scope module: :public do
    	root to:"homes#top"
    end

    #public/customers
    scope module: :public do
      get 'customers/my_page' => 'customers#show', as: 'my_page'
      get 'customers/information/edit' => 'customers#edit'
      patch 'customers/information' => 'customers#update', as: 'information'
      get 'customers/bookmark' => "customers#bookmark", as: 'bookmark' #ブックマーク一覧ページ
      get 'customers/confirm' => "customers#confirm", as: 'confirm' #退会確認ページ
      patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw' #退会処理
    end

    #ゲストログインのルーティング
    devise_scope :customer do
      post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
    end


    #public/orders
    scope module: :public do
      post '/orders/confirm' => "orders#confirm"
      get '/orders/complete' => 'orders#complete', as: 'complete'
      resources :orders, only: [:new, :create, :index, :show, :edit, :destroy, :update]
    end

    scope module: :public do
      delete "cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all" #「resources:cart_items」の上にdestroy_allを持ってきたらidがつかない
      resources :cart_items, only: [:index,:update,:destroy,:create]
      resources :shipping_addresses
      get '/items/searches' => 'items#searches', as: 'searches'
      resources :items
      resources :genres, only: [:show]
      resources :contacts, only: [:new, :create, :index, :show]
      post '/contacts/confirm' => "contacts#confirm"
      post '/contacts/back' => "contacts#back", as: "back"

      resources :shops do
        member do
          get :items
        end
        resource :bookmarks, only: %i[create destroy]
      end

    end


    # 管理者用
    # URL /admin/sign_in ...
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }

    namespace :admin do
      resources :genres
      resources :items
      resources :shops
      resources :customers
      resources :orders
      resources :contacts, only: [:index, :show, :update]
    end
end

app/models/shop.rb
class Shop < ApplicationRecord
  include JpPrefecture

  def name_display
    id.to_s + ' / ' + name #idがintegerでnameがstringだからto_sをつけて数値変換してる
  end

  has_one_attached :image
  has_many :items, dependent: :destroy #shopを消したらそれに紐づいているitemsも消える
  has_many :bookmarks, dependent: :destroy

  def bookmarked_by?(customer)
    bookmarks.where(customer_id: customer).exists?
  end

  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :postal_code, presence: true
  validates :prefecture, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true


#12,15,16,17行目はenumを使用した時の記述（jp_prefectureを使用してればstring型のprefectureカラムを用意さえすればenum使わなくていい）
  # enum prefecture: { hokkaido: 0, aomori: 1, akita: 2, iwate: 3, yamagata: 4, miyagi: 5, fukushima: 6, niigata: 7, gunma: 8, tochigi: 9, ibaraki: 10, saitama: 11, yamanashi: 12, chiba: 13, tokyo: 14, kanagawa: 15, nagano: 16, shizuoka: 17, toyama: 18, ishikawa: 19, gifu: 20, fukui: 21, aichi: 22, shiga: 23, mie: 24, kyoto: 25, osaka: 26, nara: 27, hyogo: 28, wakayama: 29, tottori: 30, okayama: 31, shimane: 32, hiroshima: 33, yamaguchi: 34, kagawa: 35, tokushima: 36, ehime: 37, kochi: 38, fukuoka: 39, saga: 40, nagasaki: 41, oita: 42, kumamoto: 43, miyazaki: 44, kagoshima: 45, okinawa: 46 }

  #def self.prefecture_i18n_names
    #prefectures.map {|k, v| [I18n.t("enums.shop.prefecture.#{k}"), k]}
  #end

end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @shop=Shop.new
  end

  def create
    @shop=Shop.new(shop_params)
    if @shop.save
      flash[:notice] = "ショップの新規登録が完了しました！"
      redirect_to admin_shops_path(@shop.id)
    else
      render :new
    end
  end

  def index
     @shops=Shop.page(params[:page])
  end

  def edit
    @shop=Shop.find(params[:id])
  end

  def update
    @shop=Shop.find(params[:id])
    if @shop.update(shop_params)
      flash[:notice] = "ショップの編集内容を保存しました！"
      redirect_to admin_shops_path
    else
      render "edit"
    end
  end

  def destroy
    @shop=Shop.find(params[:id])
    @shop.destroy
    redirect_to admin_shops_path
  end

  private

  def shop_params
    params.require(:shop).permit(:image, :name, :introduction, :postal_code, :prefecture, :address, :phone_number)
  end

end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/views/admin/shops/edit.html.erb
<div class='container py-5'>
  <div class="row">
    <div class="col mt-3 text-center">
       <h4 class="font-weight-bold">商品詳細</h4>
    </div>
  </div>

  <% if @shop.errors.any? %>
    <%= @shop.errors.count %>件のエラーが発生しました
    <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class="row d-flex justify-content-center">
  <%= form_with model: @shop, url: admin_shop_path, method: :patch do |f| %>
    <div class"col-md-6">
      <table class="table text-center">
        <tbody>
            <tr>
              <th><%= f.label "ショップ画像" %></th>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>

            <tr>
              <th><%= f.label "ショップ名"%></th>
              <td><%= f.text_field :name %></td>
             </tr>

            <tr>
              <th><%= f.label "ショップ紹介"%></th>
              <td><%= f.text_area :introduction %></td>
            </tr>

            <tr>
              <th><%= f.label "郵便番号" %></th>
               <td><%= f.text_field :postal_code %></td>
            </tr>

            <tr>
              <th><%= f.label "都道府県" %></th>
              <td><%= f.collection_select :prefecture, JpPrefecture::Prefecture.all, :name, :name, { include_blank: 'ショップの所在地' } %></td>
            </tr>

            <tr>
              <th><%=f.label:"住所" %></th>
              <td><%= f.text_field :address %></td>
            </tr>

            <tr>
              <th><%=f.label:"電話番号" %></th>
              <td><%= f.text_field :phone_number %></td>
            </tr>
        </tbody>
      </table>
    </div>

    <div class="row pb-5 d-flex justify-content-center">
      <%= f.submit "変更を保存", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/admin/shops/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 m-4 text-center">
      <h4 class="font-weight-bold">ショップ一覧</h4>
    </div>
    <div class="col-12 pb-3">
      <%=link_to "ショップを追加する", new_admin_shop_path, class: "btn btn-outline-warning rounded-pill" %>
    </div>
    <div class="flash"><%= flash[:notice] %></div>

    <table class='table table-inverse text-center'>
      <thead class="thead-dark">
        <tr>
          <th>ショップID</th>
          <th>ショップ名</th>
          <th>住所</th>
          <th>電話番号</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @shops.each do |shop| %>
          <tr>
            <td><%= shop.id %></td>
            <td><%= shop.name %></td>
            <td>
              〒<%= shop.postal_code %><br>
              <%= shop.prefecture %><%= shop.address %>
            </td>
            <td><%= shop.phone_number%></td>
            <td>
              <%= link_to "編集する", edit_admin_shop_path(shop.id), class: "btn btn-outline-primary btn-sm" %>
              <%= link_to "削除する", admin_shop_path(shop.id), data: {confirm: "本当に消しますか？"}, class: "btn btn-outline-danger btn-sm", method: :delete %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate @shops %>
</div>

app/views/admin/shops/new.html.erb
<div class="container py-5" >
  <div class="row">
    <div class="col-12 mb-5 mt-3 text-center">
      <h4 class="font-weight-bold">新規ショップ登録</h4>
    </div>
    <div class="col-12">
      <% if @shop.errors.any? %>
        <%= @shop.errors.count %>件のエラーが発生しました
        <ul>
          <% @shop.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <div class="row d-flex justify-content-center">
    <%= form_with model: @shop, url: admin_shops_path, method: :post do |f| %>

      <table class="table text-center" style="margin:auto;">
        <tbody>
          <tr>
             <th><%= f.label "ショップ画像" %></th>
             <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>

          <tr>
             <th><%= f.label "ショップ名" %></th>
             <td><%= f.text_field :name, placeholder: "ショップ名" %></td>
          </tr>

          <tr>
             <th><%= f.label "ショップ紹介"%></th>
             <td><%= f.text_area :introduction, placeholder: "ここに紹介文を記述します" %></td>
          </tr>

          <tr>
             <th><%= f.label "郵便番号" %></th>
             <td><%= f.text_field :postal_code, placeholder: "郵便番号(ハイフンなし)" %></td>
          </tr>

          <tr>
            <th><%= f.label "都道府県"%></th>
            <td><%= f.collection_select :prefecture, JpPrefecture::Prefecture.all, :name, :name, { include_blank: 'ショップの所在地' } %></td>
            <!--下記はenumを使用した時の書き方-->
            <%#=f.select :prefecture, options_from_collection_for_select(Shop.prefecture_i18n_names, :last, :first), include_blank: '選択してください' %>
          </tr>

          <tr>
             <th><%=f.label:"住所" %></th>
             <td><%= f.text_field :address, placeholder: "市区町村以下の住所" %></td>
          </tr>

          <tr>
             <th><%=f.label:"電話番号" %></th>
             <td><%= f.text_field :phone_number, placeholder: "電話番号(ハイフンなし)" %></td>
          </tr>
        </tbody>
      </table>

      <div class="row d-flex justify-content-center">
        <%= f.submit "新規登録", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>