config/routes.rb
Rails.application.routes.draw do

      # 顧客用
    # URL /customers/sign_in ...
    devise_for :customers, skip: [:passwords],controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

    scope module: :public do
    	root to:"homes#top"
    end

    #public/customers
    scope module: :public do
      get 'customers/my_page' => 'customers#show', as: 'my_page'
      get 'customers/information/edit' => 'customers#edit'
      patch 'customers/information' => 'customers#update', as: 'information'
      get 'customers/bookmark' => "customers#bookmark", as: 'bookmark' #ブックマーク一覧ページ
      get 'customers/confirm' => "customers#confirm", as: 'confirm' #退会確認ページ
      patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw' #退会処理
    end

    #ゲストログインのルーティング
    devise_scope :customer do
      post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
    end


    #public/orders
    scope module: :public do
      post '/orders/confirm' => "orders#confirm"
      get '/orders/complete' => 'orders#complete', as: 'complete'
      resources :orders, only: [:new, :create, :index, :show, :edit, :destroy, :update]
    end

    scope module: :public do
      delete "cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all" #「resources:cart_items」の上にdestroy_allを持ってきたらidがつかない
      resources :cart_items, only: [:index,:update,:destroy,:create]
      resources :shipping_addresses
      get '/items/searches' => 'items#searches', as: 'searches'
      resources :items
      resources :genres, only: [:show]
      resources :contacts, only: [:new, :create, :index, :show]
      post '/contacts/confirm' => "contacts#confirm"
      post '/contacts/back' => "contacts#back", as: "back"

      resources :shops do
        member do
          get :items
        end
        resource :bookmarks, only: %i[create destroy]
      end

    end


    # 管理者用
    # URL /admin/sign_in ...
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }

    namespace :admin do
      resources :genres
      resources :items
      resources :shops
      resources :customers
      resources :orders
      resources :contacts, only: [:index, :show, :update]
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting_for_payment: 0, payment_confirmation: 1, shipping_preparation: 2, sent: 3 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @orders = Order.page(params[:page]).order(created_at: "DESC")
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def update
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @order.update(order_params)
    redirect_to request.referer
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container py-3">
  <div class="row">
    <div class="col text-center my-4">
      <div class="flash"><%= notice %></div>
      <h4><strong>注文履歴一覧</strong></h4>
    </div>
  </div>

  <table class="table table-bordered">
    <thead class="thead-dark text-center">
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>

    <tbody class="text-center">
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order.id) %></td>
          <td><%= order.name %></td>
          <td><%= order.order_items.sum(:quantity) %></td>
          <td><%= order.order_status_i18n %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @orders %>
</div>

app/views/admin/orders/show.html.erb
  <div class="container py-5">
    <h4 class="my-4 fw-bold"><strong>注文履歴詳細</strong></h4>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th class="table-secondary text-center" style="color:black;">購入者</th>
            <td><%= link_to @order.name , admin_customer_path(@order.customer.id) %></td>
          </tr>

          <tr>
            <th class="table-secondary text-center" style="color:black;">注文日</th>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>

          <tr>
            <th class="table-secondary text-center" style="color:black; vertical-align: middle; ">配送先</th>
            <td>
              〒<%= @order.postal_code %>　<%= @order.address %><br>
                <%= @order.name %>
            </td>
          </tr>

          <tr>
            <th class="table-secondary text-center" style="color:black;">支払方法</th>
            <td><%= @order.payment_method_i18n  %></td>
          </tr>

          <tr>
            <th class="table-secondary text-center" style="color:black;">注文ステータス</th>
              <td>
                <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
                  <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]}, include_blank: "選択して下さい" %>
                  <%= f.submit "更新", class: 'btn btn-outline-success' %>
                <% end %>
              </td>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <div clas ="col-md-8">
          <table class="table table-bordered mt-4">
            <thead>
              <tr class="table-secondary text-center">
                <th style="color:black;">商品名</th>
                <th style="color:black;">単価（税込）</th>
                <th style="color:black;">数量</th>
                <th style="color:black;">小計</th>
              </tr>
            </thead>

            <tbody>
              <% @order_items.each do |order_item| %>
                <tr>
                  <td><%= order_item.item.name %></td>
                  <td><%= order_item.price.to_s(:delimited) %>円</td>
                  <td><%= order_item.quantity %></td>
                  <td><%= (order_item.price * order_item.quantity).to_s(:delimited) %>円</td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <div class ="col-lg-3 offset-1">
          <table class="table table-bordered mt-4">
            <thead>
              <tr>
                <th class="table-secondary text-center"style="color:black;">商品合計</th>
                <td><%= (@order.price - @order.postage).to_s(:delimited) %>円</td>
              </tr>

              <tr>
                <th class="table-secondary text-center"style="color:black;">送料</th>
                <td><%= @order.postage.to_s(:delimited) %>円</td>
              </tr>

              <tr>
                <th class="table-secondary text-center"style="color:black;">請求金額</th>
                <td><%= @order.price.to_s(:delimited) %>円</td>
              </tr>
            </thead>
          </table>
        </div>
      </div>
  </div>