config/routes.rb
Rails.application.routes.draw do

      # 顧客用
    # URL /customers/sign_in ...
    devise_for :customers, skip: [:passwords],controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

    scope module: :public do
    	root to:"homes#top"
    end

    #public/customers
    scope module: :public do
      get 'customers/my_page' => 'customers#show', as: 'my_page'
      get 'customers/information/edit' => 'customers#edit'
      patch 'customers/information' => 'customers#update', as: 'information'
      get 'customers/bookmark' => "customers#bookmark", as: 'bookmark' #ブックマーク一覧ページ
      get 'customers/confirm' => "customers#confirm", as: 'confirm' #退会確認ページ
      patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw' #退会処理
    end

    #ゲストログインのルーティング
    devise_scope :customer do
      post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
    end


    #public/orders
    scope module: :public do
      post '/orders/confirm' => "orders#confirm"
      get '/orders/complete' => 'orders#complete', as: 'complete'
      resources :orders, only: [:new, :create, :index, :show, :edit, :destroy, :update]
    end

    scope module: :public do
      delete "cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all" #「resources:cart_items」の上にdestroy_allを持ってきたらidがつかない
      resources :cart_items, only: [:index,:update,:destroy,:create]
      resources :shipping_addresses
      get '/items/searches' => 'items#searches', as: 'searches'
      resources :items
      resources :genres, only: [:show]
      resources :contacts, only: [:new, :create, :index, :show]
      post '/contacts/confirm' => "contacts#confirm"
      post '/contacts/back' => "contacts#back", as: "back"

      resources :shops do
        member do
          get :items
        end
        resource :bookmarks, only: %i[create destroy]
      end

    end


    # 管理者用
    # URL /admin/sign_in ...
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }

    namespace :admin do
      resources :genres
      resources :items
      resources :shops
      resources :customers
      resources :orders
      resources :contacts, only: [:index, :show, :update]
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :shop

  validates :customer_id, uniqueness: { scope: :shop_id } #customer_idとshop_idは同じ組み合わせは1つだけにしてください
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  validates :quantity, numericality: { greater_than_or_equal_to: 1 } #numericality（自然数）。１もしくは１以上じゃないとダメ

  def subtotal
    item.with_tax_price * quantity #税込み価格×数量
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :customer

  validates :subject, presence: true
  validates :content, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord


#ゲストログインの情報
  def self.guest
    find_or_create_by!(last_name: 'guest' ,first_name: 'user' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.last_name = "guest"
      customer.first_name ="user"
      customer.last_name_kana = "guest"
      customer.first_name_kana ="user"
      customer.email = "guest@example.com"
      customer.postal_code = "0000000"
      customer.address = "東京都xx区"
      customer.phone_number = "00000000000"
    end
  end

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + last_name + ' ' + first_name
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_addresses
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :contacts

  has_many :bookmarks, dependent: :destroy #ブックマークのことを指してる
  has_many :bookmarks_shops, through: :bookmarks, source: :shop #shopのテーブルのことを指してる


  def bookmark?(shop) #ブックマークされたショップにこのショップは含まれてるか？
    bookmarks_shops.include?(shop)
    #Bookmark.where(customer_id: id, shop_id: s.id).exists?と同じ
  end

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :phone_number, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def name
    "#{last_name} #{first_name}"
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre, optional: true
  belongs_to :shop
  has_many :cart_items

  validates :image, presence: true
  validates :name, presence: true
  validates :detail, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  validates :shop_id, presence: true

  def with_tax_price
    (price*1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting_for_payment: 0, payment_confirmation: 1, shipping_preparation: 2, sent: 3 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
  belongs_to :customer

  validates :address, presence: true
  validates :postal_code, presence: true
  validates :name, presence: true
end

app/models/shop.rb
class Shop < ApplicationRecord
  include JpPrefecture

  def name_display
    id.to_s + ' / ' + name #idがintegerでnameがstringだからto_sをつけて数値変換してる
  end

  has_one_attached :image
  has_many :items, dependent: :destroy #shopを消したらそれに紐づいているitemsも消える
  has_many :bookmarks, dependent: :destroy

  def bookmarked_by?(customer)
    bookmarks.where(customer_id: customer).exists?
  end

  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :postal_code, presence: true
  validates :prefecture, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true


#12,15,16,17行目はenumを使用した時の記述（jp_prefectureを使用してればstring型のprefectureカラムを用意さえすればenum使わなくていい）
  # enum prefecture: { hokkaido: 0, aomori: 1, akita: 2, iwate: 3, yamagata: 4, miyagi: 5, fukushima: 6, niigata: 7, gunma: 8, tochigi: 9, ibaraki: 10, saitama: 11, yamanashi: 12, chiba: 13, tokyo: 14, kanagawa: 15, nagano: 16, shizuoka: 17, toyama: 18, ishikawa: 19, gifu: 20, fukui: 21, aichi: 22, shiga: 23, mie: 24, kyoto: 25, osaka: 26, nara: 27, hyogo: 28, wakayama: 29, tottori: 30, okayama: 31, shimane: 32, hiroshima: 33, yamaguchi: 34, kagawa: 35, tokushima: 36, ehime: 37, kochi: 38, fukuoka: 39, saga: 40, nagasaki: 41, oita: 42, kumamoto: 43, miyazaki: 44, kagoshima: 45, okinawa: 46 }

  #def self.prefecture_i18n_names
    #prefectures.map {|k, v| [I18n.t("enums.shop.prefecture.#{k}"), k]}
  #end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Revege</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="ml-5" href="/"><%=image_tag "header3.png", size:"140x90" %></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
               <div class="collapse navbar-collapse" id="navbarNavDropdown">
                 <ul class="navbar-nav ml-auto ">

                   <!--以下会員がログインした場合の表示-->
                   <% if customer_signed_in? %>
                      <li class="mr-2">
                       <%=link_to my_page_path, class:'btn btn-malformation1' do %>
                         <i class="fas fa-house-user mr-2"></i>マイページ
                       <%end%>
                      </li>

                      <li class="mr-2">
                       <%=link_to items_path, class:'btn btn-malformation1' do %>
                         <i class="fas fa-seedling mr-2"></i>商品一覧
                       <%end%>
                      </li>

                      <li class="mr-2">
                       <%=link_to cart_items_path, class:'btn btn-malformation1' do %>
                        <i class="fas fa-shopping-cart mr-2"></i>カート
                       <%end%>
                      </li>

                      <li class="mr-2 mt-5">
                       <%=link_to destroy_customer_session_path, method: :delete, class:'text-secondary border-bottom' do %>
                         ログアウト
                       <%end%>
                      </li>
                   <!--以下、管理者がログインした場合の表示-->
                   <% elsif admin_signed_in? %>
                      <li class="mr-2"><%= link_to "問い合わせ一覧", admin_contacts_path, class:'btn btn-outline-secondary btn-sm rounded-pill' %></li>
                      <li class="mr-2"><%= link_to "注文履歴一覧", admin_orders_path, class:'btn btn-outline-secondary btn-sm rounded-pill' %></li>
                      <li class="mr-2"><%= link_to "会員一覧", admin_customers_path, class:'btn btn-outline-secondary btn-sm rounded-pill' %></li>
                      <li class="mr-2"><%= link_to "商品一覧", admin_items_path, class:'btn btn-outline-secondary btn-sm rounded-pill' %></li>
                      <li class="mr-2"><%= link_to "ショップ一覧", admin_shops_path, class:'btn btn-outline-secondary btn-sm rounded-pill' %></li>
                      <li class="mr-2"><%= link_to "ジャンル一覧", admin_genres_path, class:'btn btn-outline-secondary btn-sm rounded-pill' %></li>
                      <li class="mr-2"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:'btn btn-outline-info btn-sm rounded-pill' %></li>
                   <!--以下はログインしてない場合の表示-->
                   <% else %>
                      <li class="mr-2">
                        <%=link_to new_customer_session_path, class:"btn btn-malformation" do %>
                          ログイン|会員登録
                        <%end%>
                      </li>
                   <%end%>
                </ul>
            </div>
        </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer class="footer pt-5 mt-5">
      <div class="container">
        <p class="text-center">@ReVege</p>

        <% if customer_signed_in? %>
          <ul class="d-flex justify-content-end list-unstyled p-0 m-0">
            <li class="mr-2 mt-5">
              <%= link_to new_contact_path, class:'text-secondary border-bottom' do %>
                お問い合わせはこちら！！
              <%end%>
            </li>
            <li class="mr-2 mt-5 text-secondary border-bottom">
              利用規約
            </li>
          </ul>
        <% end %>
      </div>
  　</footer>

  </body>
</html>